// Common object models

// Defines the role based equipment hierarchy level as defined in ISA 95. 
// Defined values are:
export let EquipmentElementLevelType = [
    "Enterprise",
    "Site",
    "Area",
    "ProcessCell",
    "Unit",
    "ProductionLine",
    "WorkCell",
    "ProductionUnit",
    "StorageZone",
    "StorageUnit",
    "WorkCenter",
    "WorkUnit",
    "EquipmentModule",
    "ControlModule",
    "Other"
]

export interface HierarchyScopeType {
    equipmentID: string;
    equipmentElementLevel: string;
    equipmentLevel: string;
    hierarchyScope: [];
}

export interface ValueType {
    ValueString: string;
    DataType: string;
    UnitOfMeasure: string;
    Key: [];
}

export let DataTypeType = [
    "Amount",
    "BinaryObject",
    "Code",
    "DateTime",
    "Identifier",
    "Indicator",
    "Measure",
    "Numeric",
    "Quantity",
    "Text",
    "string",
    "byte",
    "unsignedByte",
    "binary",
    "integer",
    "positiveInteger",
    "negativeInteger",
    "nonNegativeInteger",
    "nonPositiveInteger",
    "int",
    "unsignedInt",
    "long",
    "unsignedLong",
    "short",
    "unsignedShort",
    "decimal",
    "float",
    "double",
    "boolean",
    "time",
    "timeInstant",
    "timePeriod",
    "duration",
    "date",
    "dateTime",
    "month",
    "year",
    "century",
    "recurringDay",
    "recurringDate",
    "recurringDuration",
    "Name",
    "QName",
    "NCName",
    "uriReference",
    "language",
    "ID",
    "IDREF",
    "IDREFS",
    "ENTITY",
    "ENTITIES",
    "NOTATION",
    "NMTOKEN",
    "NMTOKENS",
    "Enumeration",
    "SVG",
    "Other"
]

export let UnitOfMeasureType = [
    {"name":"degrees C", "description": "degrees Celsius"},
    {"name":"degrees F", "description": "degrees Fahrenheit"},
    {"name":"A", "description": "ampere(s)"},
    {"name":"atm", "description": "standard atmosphere"},
    {"name":"AU", "description": "astronomical unit"},
    {"name":"bbl", "description": "barrel(s)"},
    {"name":"Bcf", "description": "billion cubic feet (gas flow)"},
    {"name":"Bcfd", "description": "billion cubic feet per day (gas flow)"},
    {"name":"Bcfy", "description": "billion cubic feet per year (gas flow)"},
    {"name":"Btu", "description": "British thermal unit(s)"},
    {"name":"Bunit", "description": "billion unit(s)"},
    {"name":"c", "description": "cycle(s)"},
    {"name":"c", "description": "centi (one-hundredth); prefix only"},
    {"name":"C", "description": "coulomb(s)"},
    {"name":"cal ", "description": "calorie(s)"},
    {"name":"cd", "description": "candela(s)"},
    {"name":"Ci ", "description": "curie(s)"},
    {"name":"cmil", "description": "circular mil"},
    {"name":"cp", "description": "candlepower"},
    {"name":"cpm", "description": "count(s) per minute"},
    {"name":"cps", "description": "count(s) per second"},
    {"name":"d ", "description": "day(s)"},
    {"name":"d", "description": "deci (one-tenth); prefix only"},
    {"name":"D", "description": "darcy(s)"},
    {"name":"dB", "description": "decibel(s)"},
    {"name":"dyn", "description": "dyne(s)"},
    {"name":"eV ", "description": "electron volt(s)"},
    {"name":"F", "description": "fermi(s)"},
    {"name":"F ", "description": "farad(s)"},
    {"name":"fc", "description": " footcandle(s)"},
    {"name":"fl oz", "description": "fluid ounce(s)"},
    {"name":"ft ", "description": " foot/feet"},
    {"name":"ft/s", "description": "foot/feet per second"},
    {"name":"ft<sup>2</sup>", "description": "square foot/feet"},
    {"name":"ft-lbf", "description": "foot pound(s) (force)"},
    {"name":"g ", "description": "gram(s)"},
    {"name":"g/t ", "description": "gram(s) per tonne"},
    {"name":"g, G", "description": "Gal (gravity constant)"},
    {"name":"G ", "description": "giga (one billion); prefix only"},
    {"name":"gal", "description": "gallon(s)"},
    {"name":"Gs", "description": "gauss"},
    {"name":"h", "description": "hour(s)"},
    {"name":"ha ", "description": "hectare(s)"},
    {"name":"H.E.", "description": "high explosive(s)"},
    {"name":"hp", "description": " horsepower"},
    {"name":"hp-h", "description": "horsepower hour"},
    {"name":"Hz", "description": "cycle(s) per second"},
    {"name":"in Hg", "description": "inch(es) of mercury"},
    {"name":"in", "description": "inch(es)"},
    {"name":"in H<sub>2</sub>O", "description": "inch(es) of water"},
    {"name":"J", "description": "joule(s)"},
    {"name":"k", "description": "kilo (one thousand); prefix only"},
    {"name":"K", "description": "kelvin"},
    {"name":"l", "description": "liter(s)"},
    {"name":"L", "description": "liter(s) (preferred form)"},
    {"name":"L", "description": "lambert(s)"},
    {"name":"lb ", "description": "pound(s)"},
    {"name":"lbf", "description": "pound(s) force"},
    {"name":"lbf-ft", "description": "pound(s) force foot"},
    {"name":"lt", "description": "long ton(s)"},
    {"name":"m", "description": "meter"},
    {"name":"m", "description": "milli (one-thousandth); prefix only"},
    {"name":"M", "description": "mega (one million)"},
    {"name":"Mcf", "description": "thousand cubic feet (gas flow)"},
    {"name":"Mcfd", "description": "thousand cubic feet per day"},
    {"name":"mho", "description": "mho(s)"},
    {"name":"mi", "description": "mile(s)"},
    {"name":"mil", "description": "thousandth of an inch"},
    {"name":"MMbbl", "description": "million barrels"},
    {"name":"MMcf", "description": "million cubic feet (gas flow)"},
    {"name":"MMcfd", "description": "million cubic feet per day (gas flow)"},
    {"name":"MMcfy", "description": "million cubic feet per year (gas flow)"},
    {"name":"mol", "description": "mole(s)"},
    {"name":"mol wt", "description": "mole weight"},
    {"name":"mol %", "description": "mole percent"},
    {"name":"mpg", "description": "mile(s) per gallon"},
    {"name":"mph", "description": "mile(s) per hour"},
    {"name":"Mx", "description": "maxwell(s)"},
    {"name":"n", "description": "nano (one-billionth); prefix only"},
    {"name":"n", "description": "refractive index"},
    {"name":"N", "description": "Newton(s)"},
    {"name":"nmi", "description": "nautical mile(s)"},
    {"name":"Oe", "description": "oersted(s)"},
    {"name":"ohm-cmil/ft", "description": "ohm circular mil per foot"},
    {"name":"oz", "description": "ounce(s)"},
    {"name":"p", "description": "pico (one-trillionth); prefix only"},
    {"name":"P", "description": "poise(s)"},
    {"name":"Pa", "description": "pascal(s)"},
    {"name":"pct", "description": "percent"},
    {"name":"ppb", "description": "part(s) per billion"},
    {"name":"ppm", "description": "part(s) per million"},
    {"name":"psi", "description": "pound(s) (force) per square inch"},
    {"name":"psia", "description": "pound(s) force per square inch, absolute"},
    {"name":"psig", "description": "pound(s) force per square inch, gauge"},
    {"name":"r", "description": "revolution(s)"},
    {"name":"R", "description": "roentgen(s)"},
    {"name":"rad", "description": "radian(s)"},
    {"name":"rpm", "description": "revolutions per minute"},
    {"name":"s", "description": "second(s)"},
    {"name":"S", "description": "siemens(s)"},
    {"name":"sr", "description": "steradian(s)"},
    {"name":"st", "description": "stere(s)"},
    {"name":"st", "description": "short ton(s)"},
    {"name":"St", "description": "stokes"},
    {"name":"std ft<sup>3</sup>", "description": "standard cubic foot/feet"},
    {"name":"t", "description": "metric ton(s)"},
    {"name":"t/w-h", "description": "metric ton(s) per worker hour"},
    {"name":"t/w-d", "description": "metric ton(s) per worker day"},
    {"name":"T", "description": "tesla(s)"},
    {"name":"tr oz", "description": "troy ounce(s)"},
    {"name":"unit<sup>-1</sup>", "description": "reciprocal unit"},
    {"name":"unit<sup>2</sup>", "description": "square unit (or unit squared)"},
    {"name":"unit<sup>3</sup>", "description": "cubic unit"},
    {"name":"W", "description": "watt(s)"},
    {"name":"kW", "description": "Kilowatt(s)"},
    {"name":"MW", "description": "Megawatt(s)"},
    {"name":"Wb", "description": "weber(s)"},
    {"name":"wt %, wt pct", "description": "weight percent"},
    {"name":"yd", "description": "yard(s)"},
    {"name":"yr", "description": "year(s)"},
]

export let ClassPropertyTypeType = [
    "ClassType",
    "InstanceType",
    "DefaultType",
    "Inventory",
    "Mixed",
    "Other"
]